import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/cona0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='docs/promo-six',data=JSON.parse(fs.readFileSync(`${out}/capture.json`));
const marks=[
 [{x:45,y:80,tx:315,ty:235,label:'男女主角，自由選擇'},{x:1070,y:700,tx:870,ty:540,label:'專屬帳號，累積練習紀錄'}],
 [{x:590,y:190,tx:1240,ty:360,label:'校園八景 × 八種學習主題'},{x:650,y:90,tx:1360,ty:207,label:'八顆寶石，逐關收集'}],
 [{x:65,y:120,tx:391,ty:245,label:'D 鍵：左手中指 → 左側出怪'},{x:930,y:610,tx:810,ty:540,label:'主角固定置中，打對就攻擊'}],
 [{x:60,y:120,tx:390,ty:245,label:'一題一字，練習注音選字'},{x:400,y:750,tx:165,ty:858,label:'完成輸入，再按 Enter 提交'}],
 [{x:440,y:220,tx:660,ty:427,label:'集滿八景寶石，解鎖大橋堂'},{x:850,y:640,tx:950,ty:511,label:'放置寶石後，啟動最後試練'}],
 [{x:60,y:100,tx:150,ty:32,label:'逐層挑戰，記錄最高層數'},{x:1080,y:640,tx:1080,ty:162,label:'五階段 Boss，綜合所學'}]
];
const cards=data.shots.map((s,i)=>`<section class="card" id="card-${i}"><header><span>WORD WAR / ${String(i+1).padStart(2,'0')}</span><h1>${s.title}</h1><p>${s.sub}</p></header><div class="capture"><img src="raw/${s.id}.png"><svg viewBox="0 0 1600 900"><defs><marker id="arrow${i}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6" fill="#ffdf76"/></marker></defs>${marks[i].map(m=>`<path d="M${m.x+180},${m.y+48} L${m.tx},${m.ty}" stroke="#071b2b" stroke-width="8" fill="none"/><path d="M${m.x+180},${m.y+48} L${m.tx},${m.ty}" stroke="#ffdf76" stroke-width="3" fill="none" marker-end="url(#arrow${i})"/><rect x="${m.x}" y="${m.y}" width="420" height="51" rx="10" fill="#071b2b" fill-opacity=".95" stroke="#ffdf76" stroke-width="2"/><text x="${m.x+16}" y="${m.y+34}" fill="#fff1b9" font-size="24" font-weight="bold">${m.label}</text>`).join('')}</svg></div><footer>${s.notes.map((n,j)=>`<div><b>${j+1}</b><article><strong>${n[0]}</strong><p>${n[1]}</p></article></div>`).join('')}</footer><small>實際遊戲畫面・本機示範帳號・展示進度非學生實績</small></section>`).join('');
fs.writeFileSync(`${out}/gallery.html`,`<!doctype html><meta charset="utf-8"><title>Word War 六張宣傳圖</title><style>*{box-sizing:border-box}body{margin:0;background:#061624;font-family:'Microsoft JhengHei',sans-serif;color:#fff}.card{width:1600px;height:1200px;background:linear-gradient(130deg,#071a2c,#12334c);position:relative;overflow:hidden;margin:0 0 30px}header{height:170px;padding:24px 48px}header span{color:#f3ca69;font-size:19px;letter-spacing:3px}h1{font-size:46px;margin:8px 0}header p{font-size:23px;margin:0;color:#c2d9e6}.capture{position:relative;width:1504px;height:846px;margin:0 48px;border:2px solid #d7b45b;border-radius:12px;overflow:hidden}.capture img{width:100%;height:100%;object-fit:contain}.capture svg{position:absolute;inset:0;width:100%;height:100%}footer{display:flex;gap:35px;padding:18px 48px}footer>div{display:flex;gap:14px;width:50%}footer b{background:#ffe087;color:#092035;border-radius:50%;width:35px;height:35px;text-align:center;line-height:35px;font-size:22px}footer strong{font-size:24px;color:#ffe087}footer p{font-size:19px;margin:4px 0;color:#d1e3ec}small{position:absolute;bottom:8px;right:48px;color:#93acbd;font-size:14px}</style>${cards}`);
const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1600,height:1250}});await page.goto('http://127.0.0.1:8767/docs/promo-six/gallery.html');await page.evaluate(()=>Promise.all([...document.images].map(img=>img.decode())));await page.evaluate(()=>document.fonts.ready);for(let i=0;i<data.shots.length;i++)await page.locator(`#card-${i}`).screenshot({path:`${out}/${data.shots[i].id}-annotated.png`});console.log('Rendered six annotated real screenshots');}finally{await browser.close();}
